baseurl = "https://backyardstats.org/"
languageCode = "en-us"
title = "Backyard Statistics"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = "backyardstats"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"
    page = "/:slug/"

[[menu.main]]
    name = "Blog"
    url = "/"
[[menu.main]]
    name = "About"
    url = "/about/"
#[[menu.main]]
#    name = "GitHub"
#    url = "https://github.com/ktoutloud"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/ktoutloud"

[params]
    description = "Let's go exploring."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

